server.port: 8080

logging.level:
  com.github.d4rk3on.spring.mvc: DEBUG
  org.springframework: INFO
  org.springframework.data: INFO

# MONGODB (MongoProperties)
spring.data.mongodb:
  host: localhost
  port: 27017
  database: example

