FROM openjdk:11-stretch

ENV JAVA_OPTIONS ""

ENV DEV_PATH /usr/share
ENV APP_DIR $DEV_PATH/app

RUN adduser java_user

# Create directories for our java binaries
RUN mkdir -p $APP_DIR && chown -R java_user $APP_DIR

ENV LOG_DIR $DEV_PATH/resources/simple-example/logs
ENV LOG_FILE $LOG_DIR/simple_example.log

RUN mkdir -p $LOG_DIR && chown -R java_user $LOG_DIR

VOLUME $LOG_DIR

# Exposed ports
ENV SERVER_PORT 8080
EXPOSE $SERVER_PORT

# Add an entrypoint
COPY docker-entrypoint.sh /
RUN chmod u+x /docker-entrypoint.sh && chown java_user: /docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

# All the remaining actions will be performed as user "java_user"
USER java_user

ENV JAR_NAME @project.artifactId@-@project.version@

COPY $JAR_NAME.jar $APP_DIR/bin/

# Command to execute
CMD ["java", "${JAVA_OPTIONS}", "-jar", "${APP_DIR}/${JAR_NAME}.jar"]